/*
 * generated by Xtext 2.35.0
 */
package org.xtext.mediumProjekt.mydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
